### ISSUE TITLE
Duplicate words and the new total number of words in the book

### ISSUE THREAD

**Issue by Tiany1Pan** [edbennett/python-testing-ci#12]
1. It might be a duplicated `pytest.raises` at [Line 263](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/02-pytest-functionality.md?plain=1#L263).

2. The latest value for `None` at [Line 241](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L241), [Line 271](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L271), [Line 306](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L306), [Line 334](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L334), [Line 368](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L368) and [Line 396](https://github.com/edbennett/python-testing-ci/edit/gh-pages/_episodes/03-fixtures.md?plain=1#L396) is 566334.

3. You may have been aware of the `doctests` issue.

**Comment by edbennett** [comment]
Ah, `pytest.raises` is supposed to be a reference to the external link, but there's a typo so it doesn't get recognised. That's an easy fix.
