### ISSUE TITLE
Learning opportunity: Reduce testing need by reducing code duplication

### ISSUE THREAD

**Issue by chillenzer** [edbennett/python-testing-ci#16]
There is an additional `subtract_arrays` that is duplicated code to `add_arrays` in that it is identical except for one minus sign. This would be a great opportunity to showcase how reducing code duplication can reduce errors and the need for testing:

If we would (maybe after the fact during the lesson) define `subtract_arrays` as
```python3
def subtract_arrays(a, b):
    return add_arrays(a, (-x for x in b))
```
this would make most testing of `subtract_arrays` redundant. As they would likely agree that they would have to copy most of the tests between `add_arrays` and `subtract_arrays` (or have the function as part of the parameter list), that could be a very plastic example of how this provably reduces the number of possible errors by almost a factor of 2.

**Comment by edbennett** [comment]
I don't think I would do that during the lesson—that is a refactoring step that I would put outside of the scope of testing.

I'm not sure about changing the code provided. The code as is deliberately uses very simple syntax, so introducing a generator expression would not be welcome I don't think.

You could imagine instead introducing a function `negate(a)`, and then using `add_arrays(a, negate(b))`. That would give another function to test, and there would be an implicit assumption that this didn't introduce another class of bug. (Are you _certain_ that $a - b \equiv a + (-b)$ for all types you're testing?)
